language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '11'
  #- '8'
  #- '6'
jobs:
  include:
    - stage: build
      node_js:
        - '10'
        - '11'
      script: npm run test:prod && npm run build
    - stage: deploy
      node_js:
        - '11'
      script: npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
