blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/biggyspender/ts-iterable-functions/discussions
    about: Please discuss non bug-related topics there
